remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
title: Agent Panel Downloads
description: Download Agent Panel for your platform
show_downloads: false
github:
  is_project_page: true
  repository_url: https://github.com/warung-madura/agh
